import './globals.css'
import Footer from '@/components/Footer'
import dynamic from 'next/dynamic';
const Email123 = dynamic(() => import('@/components/Nav'), {
  ssr: false
});
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className=' font-sans' lang="en">
      <body>

        <Email123 />
        {children}
        <Footer /></body>
    </html>
  )
}
