import Nav from '@/components/Nav'
import './globals.css'
import Footer from '@/components/Footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className=' font-sans' lang="en">
      <body>


        {children}
        <Footer /></body>
    </html>
  )
}
